// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKnCMKKTayUZxefw-rYxIw94i3rFOuBk',
    appId: '1:1013226217647:web:43b952f2fc1eb02f0bf45a',
    messagingSenderId: '1013226217647',
    projectId: 'luxesseproject',
    authDomain: 'luxesseproject.firebaseapp.com',
    storageBucket: 'luxesseproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzNInTAXPZD1LitdwDBPcgmwUi4IHWqM8',
    appId: '1:1013226217647:android:74714b7334e9f0a50bf45a',
    messagingSenderId: '1013226217647',
    projectId: 'luxesseproject',
    storageBucket: 'luxesseproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaSKgW4XLAyN-4rOjpBOTzJqjYJV5wsyA',
    appId: '1:1013226217647:ios:c5a5213bd17cd9ff0bf45a',
    messagingSenderId: '1013226217647',
    projectId: 'luxesseproject',
    storageBucket: 'luxesseproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaSKgW4XLAyN-4rOjpBOTzJqjYJV5wsyA',
    appId: '1:1013226217647:ios:c5a5213bd17cd9ff0bf45a',
    messagingSenderId: '1013226217647',
    projectId: 'luxesseproject',
    storageBucket: 'luxesseproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiKnCMKKTayUZxefw-rYxIw94i3rFOuBk',
    appId: '1:1013226217647:web:0a1459a9f1ee57ed0bf45a',
    messagingSenderId: '1013226217647',
    projectId: 'luxesseproject',
    authDomain: 'luxesseproject.firebaseapp.com',
    storageBucket: 'luxesseproject.firebasestorage.app',
  );
}
