// ─────────────────────────────────────────────────────────────────────
// SETUP REQUIRED before running:
//   1. Create a Firebase project at console.firebase.google.com
//   2. Add Android / iOS apps to the project
//   3. Run:  dart pub global activate flutterfire_cli
//            flutterfire configure
//      This generates lib/firebase_options.dart automatically.
//   4. Run:  flutter pub get
// ─────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure
import 'onboard_page.dart';
import 'home_page.dart';
// ← comment out after running once

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // ── DATA MIGRATION ──────────────────────────────────────────
  // Uncomment the line below, hot-restart once, then comment it out again.
  // await DataMigration.uploadProducts();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Luxesse',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFA68A27)),
        useMaterial3: true,
      ),
      // Auth-gate: skip login screen if user is already signed in
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Still resolving auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              backgroundColor: Color(0xFFD4B06A),
              body: Center(
                child: CircularProgressIndicator(color: Colors.white),
              ),
            );
          }
          // User is logged in → go straight to Home
          if (snapshot.hasData) return const HomePage();
          // Not logged in → show Login
          return const OnboardPage();
        },
      ),
    );
  }
}
